POST http://localhost:3000/api/skill
Content-Type: application/json

{
    "name": "PHP"
}
###
GET http://localhost:3000/api/skill

###
PUT http://localhost:3000/api/skill
Content-Type: application/json

{
    "id": "3",
    "name": "CSS"
}

###
DELETE http://localhost:3000/api/skill
Content-Type: application/json

{
    "name": "CSS"
}