POST http://localhost:3000/api/skill
Content-Type: application/json

{
    "name": "CSS"
}
###
GET http://localhost:3000/api/skill

###
PUT http://localhost:3000/api/skill
Content-Type: application/json

{
    "id": "4",
    "name": "CSS"
}

###
DELETE http://localhost:3000/api/skill
Content-Type: application/json

{
    "name": "CSS"
}