
POST http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name": "Rohan M"
}
###
GET http://localhost:3000/api/wilder

###
PUT http://localhost:3000/api/wilder
Content-Type: application/json

{
    "id": "18",
    "name": "Charlotte Kieffer"
}
###
DELETE http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name": "Charlotte Kieffer"
}

###
PUT http://localhost:3000/api/addSkill
Content-Type: application/json

{
    "wilderName": "Rohan M",
    "skillName": "CSS" 
}